#!/usr/bin/env python3
"""Create a new R package; refuse every non-empty destination."""

import argparse
from datetime import date
import json
from pathlib import Path
import re
import sys


def single_line(value):
    if not value.strip() or any(ord(c) < 32 for c in value):
        raise argparse.ArgumentTypeError("Supply a non-empty single-line value.")
    return value.strip()


def package_name(value):
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9.]*[A-Za-z0-9]", value):
        raise argparse.ArgumentTypeError(
            "Package name needs at least two characters; letters/digits/dots, "
            "starting with a letter and ending with a letter or digit."
        )
    return value


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", type=Path, help="New or empty package directory")
    parser.add_argument("--name", required=True, type=package_name)
    parser.add_argument("--title", required=True, type=single_line)
    parser.add_argument("--description", required=True, type=single_line)
    parser.add_argument("--given", required=True, type=single_line)
    parser.add_argument("--family", required=True, type=single_line)
    parser.add_argument("--email", required=True, type=single_line)
    parser.add_argument("--license", required=True, choices=("MIT", "GPL-3"))
    parser.add_argument("--year", type=int, default=date.today().year)
    parser.add_argument("--vignette", action="store_true", help="Add a knitr Rmd starter")
    args = parser.parse_args(argv)
    if not re.fullmatch(r"[^\s@]+@[^\s@]+\.[^\s@]+", args.email):
        parser.error("Supply a valid maintainer email; identity must be real.")
    if not 1900 <= args.year <= 9999:
        parser.error("License year must be between 1900 and 9999.")
    root = args.path.expanduser().resolve()
    if root.exists() and (not root.is_dir() or any(root.iterdir())):
        parser.error(f"Refusing non-empty or non-directory destination: {root}")
    # JSON string escaping is also valid for R strings; never execute author input.
    quote = lambda s: json.dumps(s, ensure_ascii=True)
    license_field = "MIT + file LICENSE" if args.license == "MIT" else "GPL-3"
    suggests = "testthat (>= 3.0.0)" + (", knitr, rmarkdown" if args.vignette else "")
    files = {
        "DESCRIPTION": (
            f"Package: {args.name}\nTitle: {args.title}\nVersion: 0.0.0.9000\n"
            f"Authors@R: person(given = {quote(args.given)}, family = {quote(args.family)},\n"
            f"    email = {quote(args.email)}, role = c(\"aut\", \"cre\"))\n"
            f"Description: {args.description}\nLicense: {license_field}\n"
            f"Encoding: UTF-8\nSuggests: {suggests}\nConfig/testthat/edition: 3\n"
            + ("VignetteBuilder: knitr\n" if args.vignette else "")
        ),
        "NAMESPACE": "# Generated by roxygen2: do not edit by hand\n",
        f"R/{args.name}-package.R": (
            "#' @keywords internal\n"
            '\"_PACKAGE\"\n'
        ),
        "tests/testthat.R": (
            "library(testthat)\n"
            f"library({args.name})\n\n"
            f"test_check({quote(args.name)})\n"
        ),
        ".Rbuildignore": (
            "^\\.git$\n^\\.github$\n^\\.agents$\n^\\.codex$\n^\\.Rproj\\.user$\n"
            "^.*\\.Rproj$\n^README\\.Rmd$\n^cran-comments\\.md$\n"
            "^check-artifacts$\n^engineering-notes\\.md$\n"
        ),
        ".gitignore": ".Rhistory\n.RData\n.Rproj.user/\n*.tar.gz\n*.Rcheck/\ncheck-artifacts/\n",
        "README.md": (
            f"# {args.name}\n\n{args.description}\n\n"
            "This is an initial package scaffold. Implement the public API, add behavior\n"
            "tests under tests/testthat, generate documentation with roxygen2, and run\n"
            "a full source-tarball R CMD check before describing it as usable.\n"
        ),
        "NEWS.md": f"# {args.name} 0.0.0.9000\n\n* Initial development.\n",
    }
    if args.license == "MIT":
        files["LICENSE"] = f"YEAR: {args.year}\nCOPYRIGHT HOLDER: {args.given} {args.family}\n"
    if args.vignette:
        files["vignettes/introduction.Rmd"] = (
            '---\ntitle: "Introduction"\noutput: rmarkdown::html_vignette\nvignette: >\n'
            '  %\\VignetteIndexEntry{Introduction}\n  %\\VignetteEngine{knitr::rmarkdown}\n'
            '  %\\VignetteEncoding{UTF-8}\n---\n\n'
            f"```{{r setup}}\nlibrary({args.name})\n```\n\n"
            "This package is at the scaffold stage. Develop this vignette into a\n"
            "runnable user workflow when the public API is implemented.\n"
        )
    root.mkdir(parents=True, exist_ok=True)
    for folder in ("R", "man", "tests/testthat"):
        (root / folder).mkdir(parents=True, exist_ok=True)
    for relative, content in files.items():
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("x", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
    print(f"Created scaffold: {root}. Add API/tests and regenerate docs before checking.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
